In [1]:
# Import NumPy for numerical operations and array manipulation
import numpy as np

***ndarray***

ndarray is the main class in NumPy, representing a multidimensional array of homogeneous data types. It provides efficient storage and manipulation of large datasets.


***np.array()***

np.array() is a NumPy function used to create an ndarray object from sequences such as lists or tuples

In [2]:
# Vector(1D array)
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
# Create an array of numbers from 1 to 100 with a step of 10
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [4]:
# Create an array of 10 numbers evenly spaced between 1 and 10
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
x = np.linspace(1, 10, 10)
y = 2 * x
y

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [6]:
# creates a 1D array with 3 elements:
np.zeros(5, )

array([0., 0., 0., 0., 0.])

In [7]:
# creates a 1D array with 3 elements:
np.ones(3, )

array([1., 1., 1.])

In [8]:
# 2D array(Matrix)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### NumPy 2D Array

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
```

**Shape: `(3, 3)`**

```text
3 → Rows
3 → Columns
```

Think of it as:

```text
       Columns
       ↓  ↓  ↓
      0  1  2
     ┌─────────
Row 0│ 1  2  3
Row 1│ 4  5  6
Row 2│ 7  8  9
```

### Remember

```text
2D → Rows → Columns

shape = (rows, columns)
```

In [9]:
# creates a 2D array with 3 rows and 4 columns filled with zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# creates a 2D array with 3 rows and 1 column filled with ones
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [11]:
# creates a 2D array with 4 rows and 3 columns filled with ones
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# Identity matrix
np.eye(1)

array([[1.]])

In [14]:
# Diagonal matrix
np.diag([1, 6, 3])

array([[1, 0, 0],
       [0, 6, 0],
       [0, 0, 3]])

### NumPy 3D Array

```
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])
```

**Shape: `(1, 3, 3)`**

```text
1 → Layer
3 → Rows
3 → Columns
```

Think of it as:

```text
        Layer 0
     ┌─────────────┐
     │ 1   2   3   │  ← Row 0
     │ 4   5   6   │  ← Row 1
     │ 7   8   9   │  ← Row 2
     └─────────────┘
       ↑   ↑   ↑
     Columns
```

### Remember

```text
3D array
   ↓
Layers → Rows → Columns
```

**`shape = (layers, rows, columns)`**

In [15]:
# 3D array(Tensor) with 1 matrix, 3 rows, and 3 columns
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
arr.shape

(1, 3, 3)

In [17]:
# 3D array(Tensor) with 2 matrices, 3 rows, and 3 columns
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [18]:
arr.shape

(2, 3, 3)

In [19]:
# 3D array(Tensor)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
# 3D array(Tensor)
np.ones((3, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

🧠 Question 1
What is the dimension of this array?
arr = np.array([1, 2, 3, 4])
Is it:
A) 1D
B) 2D
C) 3D
Your answer? 👇

In [21]:
arr = np.array([1, 2, 3, 4])
arr.shape

(4,)

🧠 Question 2
What is the dimension of this array?
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A) 1D
B) 2D
C) 3D
Your answer? 👇

In [22]:
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

arr.shape

(2, 3)

🧠 Question 3
What is the dimension of this array?
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
A) 1D
B) 2D
C) 3D
Your answer? 👇

In [23]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ], 
    [
        [5, 6], 
        [7, 8]
    ]
])

arr.shape

(2, 2, 2)

🧠 Question 4 — zeros
What does this create?
np.zeros((3, 4))
A) 1D array with 3 elements
B) 2D array with 3 rows and 4 columns
C) 3D array with 3 layers, 4 rows, and 4 columns
Your answer? 👇

In [24]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

🧠 Question 5 — ones
What is the dimension of:
np.ones((3,))
A) 1D
B) 2D
C) 3D
And tell me why. 👇

In [25]:
np.ones((3,))

array([1., 1., 1.])

🧠 Question 6 — shape
If we have:
arr = np.zeros((5, 2))
What is:
arr.shape
A) (2, 5)
B) (5, 2)
C) (5,)
Your answer? 👇

In [26]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

🧠 Question 7 — eye
What is the shape and dimension of:
np.eye(4)
A) 1D, shape (4,)
B) 2D, shape (4, 4)
C) 3D, shape (4, 4, 4)
Your answer? 👇

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🧠 Question 8 — diag
What does this create?
np.diag([1, 2, 3])
A) A 1D array: [1, 2, 3]
B) A 2D matrix:
1 0 0
0 2 0
0 0 3
C) A 3D array
Your answer? 👇

In [28]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

🧠 Question 9 — linspace
What does this produce?
np.linspace(0, 10, 5)
A) [0, 2, 4, 6, 8]
B) [0, 2.5, 5, 7.5, 10]
C) [0, 2, 4, 6, 8, 10]
Your answer? 👇

In [29]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

🧠 Question 10 — arange
What does this produce?
np.arange(0, 10, 2)
A) [0, 2, 4, 6, 8]
B) [0, 2, 4, 6, 8, 10]
C) [2, 4, 6, 8, 10]
Your answer? 👇

In [30]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

***dtype***

.dytype is an attribute, not a method/function


In [31]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [32]:
arr = np.array([1, 2, 3], dtype= np.float64)
arr

array([1., 2., 3.])

In [33]:
# Create a 1D array of integers
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [34]:
# Create a 1D array of integers with a specific data type (int32)
arr = np.array([1, 2, 3, 4], dtype= np.int32)
arr.dtype

dtype('int32')

In [35]:
# uint8 is an unsigned integer data type that can represent values from 0 to 255. It is commonly used in image processing and other applications where memory efficiency is important.
arr = np.array([-10, 20, 30], dtype=np.uint8)
arr.dtype

OverflowError: Python integer -10 out of bounds for uint8

In [36]:
# Create a 1D array of floats
arr = np.array([1.0, 2.0, 3.0])
arr.dtype

dtype('float64')

In [37]:
# Create a 1D array of floats with a specific data type (float32)
arr = np.array([1.0, 2.0, 3.0], dtype= np.float32)
arr.dtype

dtype('float32')

***reshape()***

reshape() is used to change the shape of an array without changing its data.

In [38]:
# creating a 6x6 matrix with values from 0 to 35(reshaping a 1D array to 2D)
np.arange(36).reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

***Indexing and Slicing NumPy Arrays***

In [39]:
#indexing and slicing a vector(1D arrays)
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [40]:
# Indexing a vector(1D arrays)
arr[0]

np.int64(10)

In [41]:
# Indexing a vector(1D arrays)
arr[-1]

np.int64(50)

In [42]:
#slicing a vector(1D arrays)
arr[0:3]

array([10, 20, 30])

In [43]:
# Indexing and slicing a matrix (2D array)

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# Indexing a matrix(2D arrays)
x[0, 1]

np.int64(2)

In [45]:
#slicing a matrix(2D arrays)
x[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [46]:
# slicing a matrix(2D arrays)
x[:2, :2]

array([[1, 2],
       [4, 5]])

In [47]:
# slicing a matrix(2D arrays) 
arr = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
])
arr[::2, ::2]

array([[1, 3],
       [7, 9]])

***Advanced Indexing Techniques:***
1) boolean indexing
2) fancy indexing

In [48]:
# boolean indexing
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, False, True, True])
arr[mask]

array([1, 4, 5])

In [49]:
# boolean indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]



array([4, 5])

In [50]:
# boolean indexing
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 3]

array([4, 5])

In [51]:
# boolean indexing
arr = np.array([10, 20, 30, 40, 50])
arr[(arr > 20) & (arr < 50)]

array([30, 40])

In [52]:
# boolean indexing
arr = np.array([10, 20, 30, 40, 50])
arr[(arr < 20) | (arr > 40)]

array([10, 50])

In [80]:
# boolean indexing
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr[arr > 50]

array([60, 70, 80, 90])

In [54]:
# boolean indexing
arr = np.array([10, 20, 30, 40, 50])
arr[arr > 30] = 0
arr

array([10, 20, 30,  0,  0])

In [55]:
# fancy indexing in 1D arrays
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 4])
result = arr[indices]
result

array([20, 40, 50])

In [85]:
# fancy indexing in 1D array
arr = np.array([20, 30, 50, 60, 80])
indices = np.array([0, 2, 4])
result = arr[indices]
result

array([20, 50, 80])

In [56]:
# fancy indexing in 2D arrays
arr_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = arr_2D[row_indices, col_indices]
result

array([2, 6, 7])

In [90]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
    ])

row = np.array([0, 2])
column = np.array([1, 2])
result = arr[row, column]
result


array([20, 90])

***Combining Indexing and Slicing***

In [57]:
arr = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
# combining Indexing and Slicing
arr = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
arr[1: , [0, 2]]

array([[4, 6],
       [7, 9]])

In [59]:
# combining Indexing and Slicing
arr = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
arr[arr[ : , 1] > 3]

array([[4, 5, 6],
       [7, 8, 9]])

More practice in Numpy Indexing and Slicing Practice

1. 1D Indexing & Slicing — Basic

arr = np.array([10, 20, 30, 40, 50, 60, 70])

Get:
- the third element
- the last element
- elements from index 1 to 4
- every second element

In [60]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
arr[3]


np.int64(40)

In [61]:
# 1
arr[-1]

np.int64(70)

In [62]:
# 2
arr[1: 4]

array([20, 30, 40])

In [63]:
# 3
arr[: :2]

array([10, 30, 50, 70])

2. 2D Indexing — Rows & Columns


arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


Extract:
- the element 50
- the second row
- the third column
- the top-left 2 × 2 subarray

In [64]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [65]:
# 1
arr[1 , 1]


np.int64(50)

In [66]:
# 2
arr[1, :]

array([40, 50, 60])

In [67]:
# 3
arr[: 2, : 2]


array([[10, 20],
       [40, 50]])

3. Boolean Masking — Important ⭐

arr = np.array([12, 5, 18, 3, 25, 9, 30])

Using boolean masking, create a new array containing only values greater than 10.

Then create another array containing values between 5 and 20, inclusive.

In [68]:
arr = np.array([12, 5, 18, 3, 25, 9, 30])

In [69]:
arr[arr > 10]

array([12, 18, 25, 30])

In [70]:
arr[(arr >5) & (arr < 20)]

array([12, 18,  9])

2D Masking 

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


1. What does arr[:, 1] produce?
2. What does arr[:, 1] > 3 produce?
3. How is that Boolean array used to index arr?

In [71]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [72]:
# 1
arr[:, 1]

array([2, 5, 8])

In [73]:
# 2
arr[:, 1] > 3

array([False,  True,  True])

In [74]:
# 3
arr[arr[: , 1] > 3] 

array([[4, 5, 6],
       [7, 8, 9]])

5. Combination — Slicing + Masking ⭐⭐⭐
arr = np.array([
    [10, 15, 20, 25],
    [30, 35, 40, 45],
    [50, 55, 60, 65],
    [70, 75, 80, 85]
])
Using indexing/slicing/masking:
a) Select the middle two rows and middle two columns.
b) From the last two rows, select only values greater than 60.
c) Select the second column, then keep only values greater than 30.

In [75]:
arr = np.array([
    [10, 15, 20, 25],
    [30, 35, 40, 45],
    [50, 55, 60, 65],
    [70, 75, 80, 85]
])

In [76]:
# 1
arr[1:3, 1:3]

array([[35, 40],
       [55, 60]])

In [77]:
# 2
arr[-2:][arr[-2:] > 60]

array([65, 70, 75, 80, 85])

In [78]:
# 3
arr[:, 1][arr[:, 1] > 30]

array([35, 55, 75])