In [68]:
# Import NumPy for numerical operations and array manipulation
import numpy as np

In [69]:
# np.array() is a NumPy function used to create an ndarray object from sequences such as lists or tuples
np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [70]:
# Vector(1D array)
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [71]:
# Create an array of numbers from 1 to 100 with a step of 10
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [72]:
# Create an array of 10 numbers evenly spaced between 1 and 10
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [73]:
x = np.linspace(1, 10, 10)
y = 2 * x
y

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [74]:
# 2D array(Matrix)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.ones(3,)

array([1., 1., 1.])

In [78]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
# Identity matrix
np.eye(1)

array([[1.]])

In [80]:
# Diagonal matrix
np.diag([1, 6, 3])

array([[1, 0, 0],
       [0, 6, 0],
       [0, 0, 3]])

In [81]:
# 3D array(Tensor)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
# 3D array(Tensor)
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [84]:
# 3D array(Tensor)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [86]:
# 3D array(Tensor)
np.ones((3, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [87]:
# variable.shape
np.shape(arr)

(2, 3, 3)

In [88]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [103]:
# 2D array(Matrix)
arr1 = np.array([[3, 5, 6, 3], [2, 4, 6, 3], [7, 8, 9, 3]])
arr1

array([[3, 5, 6, 3],
       [2, 4, 6, 3],
       [7, 8, 9, 3]])

In [104]:
# variable.shape
np.shape(arr1)

(3, 4)