In [1]:
# Import NumPy for numerical operations and array manipulation
import numpy as np

In [2]:
# ndarray is the main class in NumPy, representing a multidimensional array of homogeneous data types. It provides efficient storage and manipulation of large datasets.
ndarray

NameError: name 'ndarray' is not defined

In [3]:
# np.array() is a NumPy function used to create an ndarray object from sequences such as lists or tuples
np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [4]:
# Vector(1D array)
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [5]:
# Create an array of numbers from 1 to 100 with a step of 10
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [6]:
# Create an array of 10 numbers evenly spaced between 1 and 10
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
x = np.linspace(1, 10, 10)
y = 2 * x
y

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [8]:
# creates a 1D array with 3 elements:
np.zeros(5, )

array([0., 0., 0., 0., 0.])

In [9]:
# creates a 1D array with 3 elements:
np.ones(3, )

array([1., 1., 1.])

In [10]:
# 2D array(Matrix)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



3 → rows
3 → columns

In [11]:
# creates a 2D array with 3 rows and 4 columns filled with zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# creates a 2D array with 3 rows and 1 column filled with ones
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [13]:
# creates a 2D array with 4 rows and 3 columns filled with ones
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Identity matrix
np.eye(1)

array([[1.]])

In [16]:
# Diagonal matrix
np.diag([1, 6, 3])

array([[1, 0, 0],
       [0, 6, 0],
       [0, 0, 3]])

In [17]:
# 3D array(Tensor)
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])


1 → layer
3 → rows
3 → columns

In [18]:
arr.shape

(1, 3, 3)

In [19]:
# 3D array(Tensor)
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
arr.shape

(2, 3, 3)

In [21]:
# 3D array(Tensor)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
# 3D array(Tensor)
np.ones((3, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

🧠 Question 1
What is the dimension of this array?
arr = np.array([1, 2, 3, 4])
Is it:
A) 1D
B) 2D
C) 3D
Your answer? 👇

In [23]:
arr = np.array([1, 2, 3, 4])
arr.shape

(4,)

🧠 Question 2
What is the dimension of this array?
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A) 1D
B) 2D
C) 3D
Your answer? 👇

In [24]:
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

arr.shape

(2, 3)

🧠 Question 3
What is the dimension of this array?
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
A) 1D
B) 2D
C) 3D
Your answer? 👇

In [25]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ], 
    [
        [5, 6], 
        [7, 8]
    ]
])

arr.shape

(2, 2, 2)

🧠 Question 4 — zeros
What does this create?
np.zeros((3, 4))
A) 1D array with 3 elements
B) 2D array with 3 rows and 4 columns
C) 3D array with 3 layers, 4 rows, and 4 columns
Your answer? 👇

In [26]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

🧠 Question 5 — ones
What is the dimension of:
np.ones((3,))
A) 1D
B) 2D
C) 3D
And tell me why. 👇

In [27]:
np.ones((3,))

array([1., 1., 1.])

🧠 Question 6 — shape
If we have:
arr = np.zeros((5, 2))
What is:
arr.shape
A) (2, 5)
B) (5, 2)
C) (5,)
Your answer? 👇

In [28]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

🧠 Question 7 — eye
What is the shape and dimension of:
np.eye(4)
A) 1D, shape (4,)
B) 2D, shape (4, 4)
C) 3D, shape (4, 4, 4)
Your answer? 👇

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🧠 Question 8 — diag
What does this create?
np.diag([1, 2, 3])
A) A 1D array: [1, 2, 3]
B) A 2D matrix:
1 0 0
0 2 0
0 0 3
C) A 3D array
Your answer? 👇

In [30]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

🧠 Question 9 — linspace
What does this produce?
np.linspace(0, 10, 5)
A) [0, 2, 4, 6, 8]
B) [0, 2.5, 5, 7.5, 10]
C) [0, 2, 4, 6, 8, 10]
Your answer? 👇

In [31]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

🧠 Question 10 — arange
What does this produce?
np.arange(0, 10, 2)
A) [0, 2, 4, 6, 8]
B) [0, 2, 4, 6, 8, 10]
C) [2, 4, 6, 8, 10]
Your answer? 👇

In [32]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

.dytype is an attribute, not a method/function


In [33]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [34]:
arr = np.array([1, 2, 3], dtype= np.float64)
arr

array([1., 2., 3.])

Indexing and Slicing Numpy arrays:

In [35]:
#indexing and slicing a vector(1D arrays)
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [36]:
# Indexing a vector(1D arrays)
arr[0]

np.int64(10)

In [37]:
# Indexing a vector(1D arrays)
arr[-1]

np.int64(50)

In [38]:
#slicing a vector(1D arrays)
arr[0:3]

array([10, 20, 30])

In [39]:
#Indexing and slicing a matrix(2D arrays)
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# Indexing a matrix(2D arrays)
x[0, 1]

np.int64(2)

In [41]:
#slicing a matrix(2D arrays)
x[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [42]:
# slicing a matrix(2D arrays)
x[:2, :2]

array([[1, 2],
       [4, 5]])

Advanced Indexing Techniques:

In [43]:
# boolean indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]



array([4, 5])

In [44]:
# boolean indexing
arr = np.array([10, 20, 30, 40, 50])
arr[(arr > 20) & (arr < 50)]

array([30, 40])

In [45]:
# boolean indexing
arr = np.array([10, 20, 30, 40, 50])
arr[(arr < 20) | (arr > 40)]

array([10, 50])

In [46]:
# boolean indexing
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[arr > 50]

array([60, 70, 80, 90])

In [47]:
# boolean indexing
arr = np.array([10, 20, 30, 40, 50])
arr[arr > 30] = 0
arr

array([10, 20, 30,  0,  0])

In [48]:
# fancy indexing in 1D arrays
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 4])
result = arr[indices]
result

array([20, 40, 50])

In [49]:
# fancy indexing in 2D arrays
arr_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = arr_2D[row_indices, col_indices]
result

array([2, 6, 7])

Combining Indexing and Slicing

In [55]:
arr = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
# combining Indexing and Slicing
arr = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
arr[1: , [0, 2]]

array([[4, 6],
       [7, 9]])

In [62]:
# combining Indexing and Slicing
arr = np.array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
arr[arr[ : , 1] > 3]

array([[4, 5, 6],
       [7, 8, 9]])