In [5]:
# Import NumPy for numerical operations and array manipulation
import numpy as np

In [14]:
# np.array() is a NumPy function used to create an ndarray object from sequences such as lists or tuples
np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [19]:
# Vector
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [25]:
# Create an array of numbers from 1 to 100 with a step of 10
vector =np.arange(1, 100, 10)
vector

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [31]:
# Create an array of 10 numbers evenly spaced between 1 and 10
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
x = np.linspace(1, 10, 10)
y = 2 * x
y

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])